spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
management:
  endpoint:
    gateway:
      enabled: true
info:
  app:
    name: API GATEWAY Default Microservice
    description: KimHengMicroServiceBank
    version: 1.0.1
