spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/loan_db
    username: "{cipher}d59a2ee717b546ca5cd25a4472c5fa53c70e09543b0aff4a11dc5d0fc7870fd8"
    password: "{cipher}2a801c23899f57f34d1d37aeb46255db9d1c6d31756a7be514ecb4754622ede5"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
info:
  app:
    name: Loan Production Microservice
